### ISSUE TITLE
request to push the merging function

### ISSUE THREAD

**Issue by tpgjs66** [sriramab/cchaid#12]
Sri, 
Would you please push the merge.R with the merging function you made?

**Comment by sriramab** [comment]
Is already online since yesterday :)

**Comment by tpgjs66** [comment]
Thanks And I'll close this issue.

**Comment by sriramab** [comment]
i suggest you do not pass y as I am doing. instead whereever there is y replace it with data[,i] and therefore you have to take away y from all function parameters.
